from pathlib import Path


# Grab my input data from the automatically-named file generated by get_data.py
def read_data(program_filename):
    filename = Path('inputs') / f'{Path(program_filename).stem}_input.txt'
    return filename.read_text()